EC2-Utilities:
  nodename: EC2-Utilities
  hostname: ec2-54-164-58-144.compute-1.amazonaws.com
  description: AWS Server - General Use - Utilities
  username: ec2-user
  osFamily: unix
  node-executor: jsch-ssh
  tags: 'ec2,demo,linux'
  ssh-key-storage-path: keys/project/PDT-Justyn/EC2Key
EC2-Kubernetes:
  nodename: EC2-Kubernetes
  hostname: ec2-54-198-187-181.compute-1.amazonaws.com
  description: AWS Server - K8s Demo Site
  username: ec2-user
  osFamily: unix
  node-executor: jsch-ssh
  tags: 'ec2,demo,linux'
  ssh-key-storage-path: keys/project/PDT-Justyn/EC2Key
EC2-Website:
  nodename: EC2-Website
  hostname: ec2-54-167-209-97.compute-1.amazonaws.com
  description: AWS Server - General Use - Website
  username: ec2-user
  osFamily: unix
  node-executor: jsch-ssh
  tags: 'ec2,demo,linux'
  ssh-key-storage-path: keys/project/PDT-Justyn/EC2Key
  sshport: 55
EC2-Windows:
  nodename: EC2-Windows
  hostname: ec2-23-20-45-89.compute-1.amazonaws.com
  description: AWS Server - General Use - Windows Utils
  username: administrator
  osFamily: windows
  node-executor: WinRMPython
  file-copier: WinRMcpPython
  tags: 'ec2,demo,windows'
  winrm-password-storage-path: keys/projects/sandbox/windows_admin
  winrm-nodeexecutor-winrmpython-interpreter: /usr/bin/python3
EC2-Hooksley:
  nodename: EC2-Hooksley
  hostname: ec2-3-91-92-212.compute-1.amazonaws.com
  description: AWS Server - Rundeck Additional Demo
  username: ec2-user
  osFamily: unix
  node-executor: jsch-ssh
  tags: 'ec2,demo,linux'
  ssh-key-storage-path: keys/project/PDT-Justyn/EC2Key
